/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ro.jtonic.ktors

import io.kotest.core.spec.style.FreeSpec
import io.kotest.matchers.shouldNotBe

class AppTest : FreeSpec() {

    init {
        "a customer should be valid (not null)" {
            Customer(id = "1", firstName = "Antonel", lastName = "Pazargic", email = "myemail@gmail.com") shouldNotBe null
        }
    }
}
